### ISSUE TITLE
encode failed

### ISSUE THREAD

**Issue by selfimprW** [facebookincubator/spectrum#1843]
2022-05-16 17:00:21.456 8516-8895/com.selfimpr.spectrumsample E/ImageManager: SpectrumException{name='codec_repo_decompressor_not_found', message='heif', location='facebook::spectrum::codecs::DecompressorProvider facebook::spectrum::codecs::Repository::decompressorProvider(const image::Format &) const:68', description='codec_repo_decompressor_not_found#heif-facebook::spectrum::codecs::DecompressorProvider facebook::spectrum::codecs::Repository::decompressorProvider(const image::Format &) const:68'}
        at com.facebook.spectrum.SpectrumHybrid.nativeTranscode(Native Method)
        at com.facebook.spectrum.SpectrumHybrid.transcode(SpectrumHybrid.java:87)
        at com.facebook.spectrum.SpectrumTask$Transcode.execute(SpectrumTask.java:93)
        at com.facebook.spectrum.Spectrum.internalExecute(Spectrum.java:138)
        at com.facebook.spectrum.Spectrum.transcode(Spectrum.java:101)
        at com.selfimpr.spectrumsample.ImageManager$resizeWithSpectrum$2.invokeSuspend(ImageManager.kt:36)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by k3b** [comment]
> SpectrumException{name='codec_repo_decompressor_not_found', message='heif', 

According to https://libspectrum.io/docs/supported_image_formats the new image format "heif" is not supported yet.

@selfimprW  can you rename this issue to "add support for heif image format" ?
