### ISSUE TITLE
Duplicate class error when including both React Native and Spectrum

### ISSUE THREAD

**Issue by vyphan** [facebookincubator/spectrum#186]
React Native version: 0.59.8
Spectrum version: 1.1.0

Tried the following, but it didn't help:
```
    implementation('com.facebook.spectrum:spectrum-default:1.1.0') {
        exclude group: 'com.facebook.spectrum', module: 'fbjni'
    }
```

> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.facebook.jni.CppException found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.CppSystemErrorException found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.DestructorThread found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.DestructorThread$1 found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.DestructorThread$Destructor found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.DestructorThread$DestructorList found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.DestructorThread$DestructorStack found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.DestructorThread$Terminus found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.HybridClassBase found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.HybridData found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.HybridData$Destructor found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.IteratorHelper found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.MapIteratorHelper found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.NativeRunnable found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.ThreadScopeSupport found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)
  Duplicate class com.facebook.jni.UnknownCppException found in modules classes.jar (com.facebook.react:react-native:0.59.8) and classes.jar (com.facebook.spectrum:spectrum-fbjni:1.1.0)

**Comment by cuva** [comment]
Hey @vyphan 

Thanks for reporting this issue. We've looking into this. I don't have a timeframe to share just yet but will update you as things move forward.

**Comment by cuva** [comment]
`fbjni` has been open sourced [here](https://github.com/facebookincubator/fbjni). It would likely make sense to make both spectrum and react native use this version to avoid conflicts.

**Comment by cxl086** [comment]
@vyphan you can  exclude `spectrum-fbjni` module

```
    implementation("com.facebook.spectrum:spectrum-default:$spectrum") {
        exclude group: 'com.facebook.spectrum', module: 'spectrum-fbjni'
    }
```

then include independent `fbjni` library, follow [set_up](https://github.com/facebookincubator/fbjni/blob/master/docs/android_setup.md)

**Comment by chevonc** [comment]
I've tried the above without success. At runtime, I hit the following SoLoaderError after following instructions above to exclude: `Java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/jni/FbJniSoLoader$SoLoaderWrapper;
        at com.facebook.spectrum.SpectrumSoLoader.init(SpectrumSoLoader.java:52)`

**Comment by cxl086** [comment]
> I've tried the above without success. At runtime, I hit the following SoLoaderError after following instructions above to exclude: `Java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/jni/FbJniSoLoader$SoLoaderWrapper; at com.facebook.spectrum.SpectrumSoLoader.init(SpectrumSoLoader.java:52)`

I copied the source to project. [FbJniSoLoader](https://github.com/facebookincubator/spectrum/blob/master/androidLibs/fbjni/java/com/facebook/jni/FbJniSoLoader.java)
