### ISSUE TITLE
Crash for Android

### ISSUE THREAD

**Issue by KennethYo** [facebookincubator/spectrum#36]
```java
2019-03-05 10:21:52.178 29826-29865/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.facebook.spectrum.sample, PID: 29826
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException
        at com.facebook.spectrum.utils.Preconditions.checkArgument(Preconditions.java:39)
        at com.facebook.spectrum.Configuration$Builder.setCompressionLevel(Configuration.java:279)
        at com.facebook.spectrum.sample.model.ConfigurationViewModel$groups$11.invoke(ConfigurationViewModel.kt:114)
        at com.facebook.spectrum.sample.model.ConfigurationViewModel$groups$11.invoke(ConfigurationViewModel.kt:45)
        at com.facebook.spectrum.sample.model.EnumParameter.udpateConfigurationBuider(ConfigurationViewModel.kt:41)
        at com.facebook.spectrum.sample.model.ConfigurationViewModel.makeConfiguration(ConfigurationViewModel.kt:58)
        at com.facebook.spectrum.sample.TranscodeAsyncTask.applyModelToOptions(TranscodeAsyncTask.kt:128)
        at com.facebook.spectrum.sample.TranscodeAsyncTask.transcode(TranscodeAsyncTask.kt:68)
        at com.facebook.spectrum.sample.TranscodeAsyncTask.doInBackground(TranscodeAsyncTask.kt:37)
        at com.facebook.spectrum.sample.TranscodeAsyncTask.doInBackground(TranscodeAsyncTask.kt:23)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by lambdapioneer** [comment]
Thanks for the bug report, this seems to be a problem with the sample app. I'll comment on the PR that was linked below :)

**Comment by lambdapioneer** [comment]
I'll close this now as the fix landed :) let me know if the issue persists when running from the latest commit on master.
